---
# Check PyCharm installation directory (check_mode indicator).
- name: Check PyCharm installation directory.
  file:
    path: "{{ pycharm_install_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: ansible_check_mode
