---
# Install Microsoft's Visual Studio Code Editor.
- block:
  - name: Add signing key 'https://packages.microsoft.com/keys/microsoft.asc'.
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Add repository 'https://packages.microsoft.com/repos/vscode stable main'.
    apt_repository: repo='deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'

  - name: Install Visual Studio Code editor.
    package: name=code state=present
  
  become: yes
  tags:
    - editor_vscode_install
    - editor_vscode
