---
# Check Eclipse CPP installation directory (check_mode indicator).
- name: Check Eclipse CPP installation directory.
  file:
    path: "{{ eclipse_cpp_install_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: ansible_check_mode
