---
- block:
  - name: Install Python v3 packages (python3, python3-dev, python3-pip).
    package: name={{ item }} state=present
    with_items:
      - python3
      - python3-dev
      - python3-pip

  - name: Install virtualenv.
    pip: name=virtualenv executable=pip3

  tags:
    - development_python_install
    - development_python
  become: yes
