---
- block:
  - name: Install Python v3 packages (python3, python3-dev, python3-pip).
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
    with_items:
      - python3
      - python3-dev
      - python3-pip

  - name: Install virtualenv.
    pip: name=virtualenv executable=pip3

  become: yes
